module Dion
  class CashFlow
    include Dion::Base

    KEYS = [ :company_code, :year_ending]
    MODEL = DataProvider::CashFlow
		RENAMED_FIELDS = {
			:pbt            => :profits_before_tax,
			:pat            => :profits_after_tax,
			:depreciatn     => :depreciation,
			:fin_lease      => :final_lease,
			:pl_sale_asst   => :pl_on_sale_of_assets,
			:pl_sale_invs   => :pl_on_sale_of_investments,
			:p_adj_s_undrt  => :profit_adj_on_sale_of_undertaking,
			:intrst_inc     => :interest_income,
			:int_paid_net   => :interest_paid_net,
			:intrst_net     => :interest_net,
			:dvdnd_rec_op   => :dividend_received_operating_activity,
			:dvdnd_net      => :dividend_net,
			:invstmts       => :investments,
			:amrtsatn_op    => :amortisation_of_exps_on_operating_activity,
			:asst_w_off     => :assets_written_off,
			:paymtto_vrs    => :payment_to_vrs,
			:prov_w_off_nt  => :provisions_written_off_net,
			:prov_graty     => :provisions_gratutity,
			:prov_dim_inv   => :provisions_dimun_in_value_of_investment,
			:prov_bdnpa     => :provisions_for_bad_debts_npa,
			:trd_recvbl     => :trade_and_other_receivables,
			:trd_bill_pur   => :trade_bills_purchased,
			:invnt_oprt     => :inventories_operating_activity,
			:trd_payble     => :trade_payble,
			:tax_provisn    => :tax_provision,
			:dirct_taxes    => :direct_taxes,
			:adv_tax_paid   => :advance_tax_paid,
			:loan_advanc    => :loans_and_advances,
			:trans_resrv    => :transfer_from_reserve,
			:oth_oprt_act   => :others_from_operating_activity,
			:pr_yr_adjust   => :prior_year_adjustments,
			:prv_writ_bck   => :provisions_written_back,
			:prior_yr_tax   => :prior_year_tax,
			:bal_writ_bck   => :balances_written_back,
			:oth_assets     => :other_assets,
			:oth_liablt     => :other_liabilites,
			:ch_in_depsit   => :change_in_deposits,
			:chin_borr      => :change_in_borrowing,
			:disc_exp_ln    => :discounts_expenses_on_loans,
			:inc_dec_advn   => :increase_or_decrease_in_advances,
			:inc_dec_invs   => :increase_or_decrease_in_investments,
			:net_stk_hire   => :net_stock_on_hire,
			:l_ast_netsal   => :leased_assets_net_of_sale,
			:exces_dep_wb   => :excess_depreciation_written_back,
			:prem_ls_land   => :premium_on_lease_of_land,
			:extr_ord_itm   => :extra_ordinary_items,
			:net_c_flow_op  => :net_cash_flow_operating_activity,
			:pur_fix_asst   => :purchase_of_fixed_assets,
			:sal_fix_asst   => :sale_of_fixed_assets,
			:cap_subs_rec   => :capital_subsidy_received,
			:pur_invst      => :purchase_of_investments,
			:sal_invst_ia   => :sale_of_investment_inves_activity,
			:aqustn_comp    => :aquisition_of_companies,
			:sal_ut_ex_itm  => :sale_of_undertaking_extra_ordinary_item,
			:int_recd       => :interest_received,
			:dvnd_recd_ia   => :dividend_received_iinvestment_activity,
			:invst_incm     => :investment_income,
			:intr_crp_dep   => :inter_corporate_deposits,
			:inv_in_subs    => :investment_in_subsidiaries,
			:loan_to_subs   => :loan_to_subsidiaries,
			:inv_in_grp_co  => :investment_in_group_co,
			:cert_dep_bnk   => :certificate_of_deposit_in_bank,
			:movmt_loans    => :movment_in_loans,
			:oth_inv_act    => :others_from_investment_activity,
			:movmt_wcap     => :movement_in_working_capital,
			:amrt_exp_ia    => :amortisation_of_exps_on_investment_activity,
			:exp_captlsd    => :expenses_capitalised,
			:ex_ord_itm_ia  => :extra_ord_items_investment_activity,
			:p_fix_ast_lo   => :purchase_of_fixed_assets_leased_out,
			:nt_id_cur_ast  => :net_increase_or_decrease_in_current_asset,
			:net_id_advn    => :net_increase_or_decrease_in_advances,
			:nt_id_cur_lib  => :net_increase_or_decrease_in_current_liabilities,
			:nt_csh_in_ia   => :net_cash_used_in_investment_activity,
			:pr_iss_eq_cap  => :proceedings_from_issue_of_equity_capital,
			:pr_iss_pr_cap  => :proceedings_from_issue__of_pref_capital,
			:pr_iss_sh_prem => :proceedings_from_issue_of_sh_capital_inclusive_share_premimum,
			:redmtn_cap     => :redemption_capital,
			:proc_iss_deb   => :proceedings_from_issue_of_debentures,
			:pr_bnk_borr    => :proceedings_from_bank_borrowings,
			:pr_l_trm_borr  => :proceedings_from_long_term_borrowings,
			:pr_sh_trm_bor  => :proceddings_from_short_term_borrowings,
			:pr_deposit     => :proceedings_from_deposits,
			:repmt_borr     => :repayment_of_borrowings,
			:sh_applictn    => :share_application,
			:ln_corp_body   => :loan_from_corporate_body,
			:dvdnd_paid     => :dividend_paid,
			:int_paid       => :interest_paid,
			:fin_chrgs      => :financial_charges,
			:csh_crdt_adv   => :cash_credit_advances,
			:csh_cap_invs   => :cash_capital_investment,
			:oth_fin_act    => :others_from_financial_activity,
			:fe_gn_los_fa   => :foreign_exchange_gain_or_loss_from_fin_activity,
			:sh_premium     => :share_premium,
			:mis_exp_w_off  => :misc_exp_written_off,
			:sal_inv_fa     => :sale_of_investments_fin_activity,
			:curr_liab      => :current_liabilities,
			:ln_disburse    => :loan_disbursed,
			:invntry_fa     => :inventory_fin_activity,
			:ex_ord_itm_fa  => :extra_ord_item_fin_activity,
			:dfrd_exp_bor   => :deferrred_exp_against_borrowing,
			:sh_aplc_rfnd   => :share_application_refund,
			:on_redem_deb   => :on_redem_of_debentures,
			:of_oth_lt_bor  => :of_other_long_term_borrowings,
			:of_sh_trm_bor  => :of_short_term_borrowings,
			:of_fin_l_liab  => :of_finance_lease_liabilities,
			:shltr_a_res    => :shelter_assisant_reserve,
			:rep_s_trm_bor  => :repayment_of_short_term_borrowings,
			:rep_l_trm_bor  => :repayment_of_long_term_borrowings,
			:nt_csh_usd_fa  => :net_cash_used_in_fin_activity,
			:fe_gn_ls_nt_fa => :foreign_exchange_gain_loss_net_in_fin_activity,
			:n_inc_dec_csh  => :net_increase_or_decrease_in_cash,
			:csh_strt_year  => :cash_start_year,
			:csh_end_year   => :cash_end_year
		}

	private
		def self.translate_fields(args)
			RENAMED_FIELDS.each { |old_name, new_name| args[new_name] = args.delete(old_name) }
			args
		end

  end
end
