class CorporateDataUpdater
  FileNames = [
      # Process these first
      'CompanyMaster.xml',
      'SchemeMaster.xml',
      # Corporate Data files
      'AccountingPolicy.xml',
      'AnnouncementsAGMBC.xml',
      'AnnouncementsBoardMeeting.xml',
      'AuditorsReport.xml',
      'AuditedResults.xml',
      'BankingRatios.xml',
      'Bonus.xml',
      'BSEPrice.xml',
      'Capitalstructure.xml',
      'CashFlow.xml',
      'CorpGovernancereport.xml',
      'DirectorsReport.xml',
      'Dividend.xml',
      'HalfyearlyResults.xml',
      'IndividualHolding.xml',
      'IndustryMaster.xml',
      'KeyExecutives.xml',
      'ListingMaster.xml',
      'News.xml',
      'NinemonthsResults.xml',
      'NotesToAccount.xml',
      'NSEPrice.xml',
      'Products.xml',
      'QuarterlyResults.xml',
      'Ratios.xml',
      'Rawmaterial.xml',
      'ShareHolding.xml',
      'Splits.xml',
      'Subsidiaries.xml',
      'CurrDetails.xml',
      #Mutual funds files
      'MfObjectives.xml',
      'NAVCP.xml',
      'NavMaster.xml',
      'FundMaster.xml',
      'MFDividendDetails.xml',
      'MFSchemeWisePortfolio.xml',
      'NAVCategoryDetails.xml',
      'MFBonusDetails.xml'
  ]
end
