development:
  host: localhost
  database: investopresto_development

test:
  host: localhost
  database: investopresto_test

# set these environment variables on your prod server
production: &production
  uri: <%= ENV['MONGOLAB_URI'] %>
  # autocreate_indexes: true
  # host: <%= ENV['MONGOID_HOST'] %>
  # port: <%= ENV['MONGOID_PORT'] %>
  # username: <%= ENV['MONGOID_USERNAME'] %>
  # password: <%= ENV['MONGOID_PASSWORD'] %>
  # database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019

staging:
  <<: *production
