require_relative 'data_provider'

module Dion
	autoload :Base,							         File.expand_path('../dion/base.rb',						            __FILE__)

	autoload :AccountingPolicy,          File.expand_path('../dion/accounting_policy.rb',           __FILE__)
	autoload :AnnouncementsAGMBC,        File.expand_path('../dion/announcements_agmbc.rb',         __FILE__)
	autoload :AnnouncementsBoardMeeting, File.expand_path('../dion/announcements_board_meeting.rb', __FILE__)
	autoload :AuditedResults,            File.expand_path('../dion/audited_results.rb',             __FILE__)
	autoload :AuditorsReport,            File.expand_path('../dion/auditors_report.rb',             __FILE__)
	autoload :BankingRatios,             File.expand_path('../dion/banking_ratios.rb',              __FILE__)
	autoload :Bonus,                     File.expand_path('../dion/bonus.rb',                       __FILE__)
	autoload :BSEPrice,                  File.expand_path('../dion/bse_price.rb',                   __FILE__)
	autoload :Capitalstructure,          File.expand_path('../dion/capitalstructure.rb',            __FILE__)
	autoload :CashFlow,                  File.expand_path('../dion/cash_flow.rb',                   __FILE__)
	autoload :CompanyMaster,             File.expand_path('../dion/company_master.rb',              __FILE__)
	autoload :CorpGovernancereport,      File.expand_path('../dion/corp_governancereport.rb',       __FILE__)
	autoload :CurrDetails,               File.expand_path('../dion/curr_details.rb',                __FILE__)
	autoload :DirectorsReport,           File.expand_path('../dion/directors_report.rb',            __FILE__)
	autoload :Dividend,                  File.expand_path('../dion/dividend.rb',                    __FILE__)
	autoload :FundMaster,                File.expand_path('../dion/fund_master.rb',                 __FILE__)
	autoload :HalfyearlyResults,         File.expand_path('../dion/halfyearly_results.rb',          __FILE__)
	autoload :IndividualHolding,         File.expand_path('../dion/individual_holding.rb',          __FILE__)
	autoload :IndustryMaster,            File.expand_path('../dion/industry_master.rb',             __FILE__)
	autoload :KeyExecutives,             File.expand_path('../dion/key_executives.rb',              __FILE__)
	autoload :ListingMaster,             File.expand_path('../dion/listing_master.rb',              __FILE__)
	autoload :MFBonusDetails,            File.expand_path('../dion/mf_bonus_details.rb',            __FILE__)
	autoload :MFDividendDetails,         File.expand_path('../dion/mf_dividend_details.rb',         __FILE__)
	autoload :MFObjectives,              File.expand_path('../dion/mf_objectives.rb',               __FILE__)
	autoload :MFSchemeWisePortfolio,     File.expand_path('../dion/mf_scheme_wise_portfolio.rb',    __FILE__)
	autoload :NAVCategoryDetails,        File.expand_path('../dion/nav_category_details.rb',        __FILE__)
	autoload :NAVCP,                     File.expand_path('../dion/navcp.rb',                       __FILE__)
	autoload :NavMaster,                 File.expand_path('../dion/nav_master.rb',                  __FILE__)
	autoload :News,                      File.expand_path('../dion/news.rb',                        __FILE__)
	autoload :NinemonthsResults,         File.expand_path('../dion/ninemonths_results.rb',          __FILE__)
	autoload :NotesToAccount,            File.expand_path('../dion/notes_to_account.rb',            __FILE__)
	autoload :NSEPrice,                  File.expand_path('../dion/nse_price.rb',                   __FILE__)
	autoload :Products,                  File.expand_path('../dion/products.rb',                    __FILE__)
	autoload :QuarterlyResults,          File.expand_path('../dion/quarterly_results.rb',           __FILE__)
	autoload :Ratios,                    File.expand_path('../dion/ratios.rb',                      __FILE__)
	autoload :Rawmaterial,               File.expand_path('../dion/rawmaterial.rb',                 __FILE__)
	autoload :SchemeMaster,              File.expand_path('../dion/scheme_master.rb',               __FILE__)
	autoload :ShareHolding,              File.expand_path('../dion/share_holding.rb',               __FILE__)
	autoload :Splits,                    File.expand_path('../dion/splits.rb',                      __FILE__)
	autoload :Subsidiaries,              File.expand_path('../dion/subsidiaries.rb',                __FILE__)
end
